// <auto-generated />
namespace SandP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InsertDataIntoSongsAndPlaylistsTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertDataIntoSongsAndPlaylistsTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201707160926442_InsertDataIntoSongsAndPlaylistsTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
